### ISSUE TITLE
rotation covariance

### ISSUE THREAD

**Issue by SubMishMar** [swri-robotics/gps_umd#13]
Why the rotation covariance is set to 99999?

**Comment by pjreed** [comment]
I'm not sure why that's the default value, as it was set long before we made a fork of the original repository.  It is exposed as a parameter, so you can manually set `rot_covariance` if you'd like.  @kriskozak , do you have any insight why the default might be set to 99999?

**Comment by kriskozak** [comment]
@pjreed is right about this being a legacy artifact, so I don't know the real reason that number was set like it is, but I assume that it was chosen to indicate that the orientation is "invalid," and it is invalid because NavSatFix messages have no orientation information.  It's an odd choice, because as far as variances go, it's confers a non-negligible amount of mathematical certainty on the measurement -- enough to possibly influence the output of an EKF, if used rather than filtered out. Unfortunately, I have lost track of whether there is a ROS standard for indicating "invalid" measurements, but I did see a reference to 1E6 possibly being one.  That also sounds low to me, and 99999.0 falls well short of that anyway.  Also as @pjreed mentions, the covariance can be set to any value you want via the `rot_covariance` parameter. We don't really know who all is using and relying on this node as-is, so I'm reluctant to make any changes to it...

**Comment by danthony06** [comment]
Given that this is a configurable parameter, and changing the default risks breaking a lot of existing code, I'm going to close this.
